### PR TITLE
Excel converter

### LINKED ISSUE #212: Add possibility to generate MS excel files
It looks that it can be done easily with small utils like this one: https://pypi.python.org/pypi/xlwt

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #212

### CODE REVIEW

**Comment by grzanka** [comment]
It looks xlwt doesn't support python 3.2 :/

**Comment by nbassler** [comment]
just let it exit then with error message "This feature is only available for Linux users."

**Comment by grzanka** [comment]
Rather "This feature is only available for Python 2.7, 3.3 and newer"

**Comment by grzanka** [comment]
@nbassler ready to be merged

**Pull request merged**
