### PR TITLE
plotting axes names

### LINKED ISSUE #223: Display axis names (X,Y,Z) on generated images

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #223

### CODE REVIEW

**Comment by grzanka** [comment]
Before:
image


After: 
image

**Comment by grzanka** [comment]
You are right, explaining it may help. But what about cylindrical coordinates:
```Position (R), Position(PHI), Position(Z)```
doesn't sound nice.

What do you think about X-coordinate, PHI-coordinate etc ?

**Comment by nbassler** [comment]
wouldn't "phi" be an "angle" or "angle segment"?

**Comment by nbassler** [comment]
R is radius.

**Comment by grzanka** [comment]
OK, so I have a proposition to change it to `Position (X,Y,Z)`, `Radius (R)`, `Angle (PHI)`

**Comment by grzanka** [comment]
Now it looks like that:
image

**Pull request merged**
