### PR TITLE
Installation documentation

### LINKED ISSUE #88: Installation instructions for windows users needed

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #88

### CODE REVIEW

**Comment by grzanka** [comment]
@nbassler any comments ? I will extend it later with matplotlib and pytrip98 installation

**Comment by grzanka** [comment]
Check this one: https://github.com/DataMedSci/pymchelper/blob/feature/88-windows-instructions/INSTALL.rst

**Comment by nbassler** [comment]
Wouldn't 98% of all users have root rights? Then i'd move all the user-only
installations far out of sight, i.e. to the bottom of the description.

Mention the simplest and most probable case first.

I will ask the windows users to try it and give feedback.

Cheers,
Niels

On 28 Sep 2016 21:01, "Leszek Grzanka" <notifications@github.com> wrote:

Check this one: https://github.com/DataMedSci/pymchelper/blob/feature/88-
windows-instructions/INSTALL.rst

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DataMedSci/pymchelper/pull/90#issuecomment-250266319>,
or mute the thread

**Comment by grzanka** [comment]
@nbassler can it be merged ?

**Pull request merged**
