### PR TITLE
DDD added

### LINKED ISSUE #111: Get ddd file directly from ShieldHit
Hey !

In order to facilitate the process of using ShieldHit with TriP, it would be interesting to get the ddd files directly from ShieldHit, using for example a ddd scorer.

Best regards,
Thomas

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #111

### CODE REVIEW

**Comment by grzanka** [comment]
@nbassler ready to be tested. Problems, to be solved in separate issues:
- [ ] documentation
- [ ] dose reproducibility (calculating energy deposition in cylindrical bin from Gaussian fits gives < 50% of the value from SHIELDHIT)
- [ ] external script which loops over set of DDD files for different energies and prepares DDD file for each of them
- [ ] code requieres a lot of cleaning and documentation

I would appreciate a chance to do it interactively and on-demand with users who need DDD-functionality.

Quick instruction how to use:
- to simply get `./outputdir/outfilename.ddd` without any futher output with 2-gaussian model:
```convertmc tripddd "data/ddd*.bdo" ./outputdir/outfilename.ddd --energy 70 --ngauss 2```
- to get basic plots ensuring fit quality, add `-v`, for more plots `-vv`, for even more plots `-vvv`.
- to get files according to 1-gaussian model, set `--ngauss 1`

**Comment by grzanka** [comment]
I suspect the test coverage will fail as I haven't provided any tests

**Comment by nbassler** [comment]
did you want to add tests prior merge? :grimacing:

**Comment by grzanka** [comment]
@nbassler I'd prefer adding tests later and first discuss with users/testers if they are happy with such code. I would appreciate help in checkig whether it's producing reasonable results.

**Pull request merged**
