### PR TITLE
missing detector title added, caused a problems with image writer

### LINKED ISSUE #98: Image converter fails because of 'title' attribute
```
convertmc --many "output/*" --converter image     
.
.
.
INFO:pymchelper.writers.plots:Writing: 21.txt.png
Traceback (most recent call last):
  File "/home/ant6/.virtualenvs/klastrotest/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/run.py", line 66, in main
    merge_many(files, parsed_args.converter, parsed_args.nan, parsed_args.colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/detector.py", line 290, in merge_many
    merge_list(group_with_same_core, core_name + ".txt", conv_names, nan, colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/detector.py", line 260, in merge_list
    first.save(output_file, conv_names, colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/detector.py", line 116, in save
    writer.write(self)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/writers/plots.py", line 85, in write
    plt.ylabel(self.make_label(detector.units[4], detector.title))
AttributeError: 'Detector' object has no attribute 'title'
```

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #98

### CODE REVIEW

**Comment by grzanka** [comment]
@ant6 can you test it and merge (i.e using github "rebase and merge" button) if it works well ?

**Comment by ant6** [comment]
@grzanka is this codecov failing normal?

**Comment by ant6** [comment]
@grzanka well, it errors :(
```
INFO:pymchelper.writers.plots:Writing: 21.txt.png
Traceback (most recent call last):
  File "/home/ant6/.virtualenvs/klastrotest/bin/convertmc", line 9, in <module>
    load_entry_point('pymchelper==0+unknown', 'console_scripts', 'convertmc')()
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper-0+unknown-py3.4.egg/pymchelper/run.py", line 66, in main
    merge_many(files, parsed_args.converter, parsed_args.nan, parsed_args.colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper-0+unknown-py3.4.egg/pymchelper/detector.py", line 290, in merge_many
    merge_list(group_with_same_core, core_name + ".txt", conv_names, nan, colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper-0+unknown-py3.4.egg/pymchelper/detector.py", line 260, in merge_list
    first.save(output_file, conv_names, colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper-0+unknown-py3.4.egg/pymchelper/detector.py", line 116, in save
    writer.write(self)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper-0+unknown-py3.4.egg/pymchelper/writers/plots.py", line 85, in write
    plt.ylabel(self.make_label(detector.units[4], detector.title))
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper-0+unknown-py3.4.egg/pymchelper/writers/plots.py", line 69, in make_label
    return name + " " + "[" + unit + "]"
TypeError: can't concat bytes to str
```

**Comment by grzanka** [comment]
Codecov complains doesn't matter. Can you send me by email the file you are trying to convert (*_fort*) ?

**Pull request merged**
