### PR TITLE
shield2fluka script

### LINKED ISSUE #20: Integrate shield2fluka input converter

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #20

### CODE REVIEW

**Comment by grzanka** [comment]
I think it should be rewritten to python. Wrapping existing C code in python is ugly.

**Comment by nbassler** [comment]
yes, fine with me to convert to python. 
But this takes time and until then, let us have the bad code here. Better this than having it nowhere.

**Comment by grzanka** [comment]
We could have the code, sure. It is just the users who would have troubles to run it: they need to get source code, compile it themselves and run it, as we cannot put easily such stuff in pip package.

**Comment by nbassler** [comment]
That would be fine with me, still better than not having access to the code at all.

**Pull request closed without merging**
